### ISSUE TITLE
code 128

### ISSUE THREAD

**Issue by ELMzouriAhmed** [w3blogfr/zebra-zpl#8]
I have a device that reads the code128 but if I put the code generate by zebra-zpl it refuses to read it, but if I put another bar-code download by web on code128 it works very well I noticed that the codes they sound different after a little research I find that ,:
There is 3 type of code128 there is code128A and code128B and code128C each of its codes generates a bar-code different on the others.
can your code  handle differing type of code128 (A-B-C) ??

j'ai un appareil qui lit le code128 mais l’orque je mais le code générer par zebra-zpl il refuse de le lire ,du coût l’orque je mais un autre code-barre télécharger par web sur le code128 il fonction très bien j'ai remarquer que les codes ils son différent après un petite recherche j'ai trouver que  ,:
il y a 3 type de code128 il y a code128A et code128B et code128C chacun de ses codes génère un code-barre déferrant de l'autre.
est ce que ton code peut gérer des différèrent type de code128(A-B-C)  ??

**Comment by w3blogfr** [comment]
Unfortunatly, I didn't work with zebra printer anymore, I could not make correct test before to commit this.

If you want, you can fork this project and create your own Class for the correct code128 that you want and make a pull request

Otherwise, if you don't want to change my code, my code allow to include native instruction : 

```
zebraLabel.addElement(new ZebraNativeZpl("^KD0\n"));
ZplUtils.zplCommand("A", "0", "R"); //will return ^A,0,R
```

Malheureusement, je n'ai plus l'occasion de travailler avec des imprimantes Zebra, et je ne pourrais pas tester mes changements avant de les partages.
Si tu le souhaite, tu peux forker mon projet et ajouter la bonne class pour autoriser ces différent type de Code128.

Sinon, tu peux également utiliser inclure des instructions natives avec zebra-zpl

```
zebraLabel.addElement(new ZebraNativeZpl("^KD0\n"));
ZplUtils.zplCommand("A", "0", "R"); //will return ^A,0,R
```

**Comment by w3blogfr** [comment]
Starting from 0.0.4, it's supported
